In [1]:
import numpy as np 

In [2]:
array = np.array([1,2,3,4,5])
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
array = array * 2
print(array)

[ 2  4  6  8 10]


In [4]:
array = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                 [[1,2,3],[4,5,6],[7,8,9]]])
print(array)
print(array.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [ ]:
z = np.array([1,2,3,4,5])

In [ ]:
z < 3

array([ True,  True, False, False, False])

In [8]:
z > 3

array([False, False, False,  True,  True])

In [9]:
z[z > 3]

array([4, 5])

In [11]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [12]:
a + b

array([ 7,  9, 11, 13, 15])

In [13]:
a + 30


array([31, 32, 33, 34, 35])

In [14]:
b * 10

array([ 60,  70,  80,  90, 100])

In [15]:
a @ b

np.int64(130)